services:
  frontend:
    container_name: frontend
    image: lsfe:1.0
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      VITE_BASE_BACKEND_URL: ${VITE_BASE_BACKEND_URL}
      VITE_BASE_FRONTEND_URL: ${VITE_BASE_FRONTEND_URL}
      # VITE_BASE_BACKEND_URL: http://backend:8000
      # VITE_BASE_FRONTEND_URL: http://localhost
