services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      MYSQL_URL=${MYSQL_URL}
      MYSQL_USER=${MYSQL_USER}
      MYSQL_PASSWORD=${MYSQL_PASSWORD}
      MYSQL_DATABASE=${MYSQL_DATABASE}
    restart: unless-stopped
